import { SavedMemo, UserSettings, MemoExportOptions } from '../types';
import { calculateMedicine } from '../utils/medicineCalc';
import { formatCurrency, formatNum, getTodayFormatted, getTimeFormatted } from '../utils/numberFormat';
import { generateMemoImage, downloadBlob } from './imageExport';
import { generateMemoPDF, downloadPDF } from './pdfExport';

export function formatMemoAsText(
  memo: SavedMemo,
  settings: UserSettings,
  options?: MemoExportOptions
): string {
  const isBn = settings.numberFormat === 'bn';
  const isMedicine = memo.type.startsWith('medicine');
  const showPrice = options?.showPrice ?? true;
  const medicineExportType = options?.medicineExportType || (memo.type === 'medicine_required' ? 'simple' : 'full');
  const lines: string[] = [];

  // Clean Header (No promotional taglines, no "MY MEMO", no "লোকাল মেমো ম্যানেজার")
  const defaultHeader = isMedicine ? '💊 ঔষধের মেমো' : '🛒 বাজারের মেমো';
  lines.push(memo.title || defaultHeader);
  if (memo.date) {
    lines.push(`তারিখ: ${memo.date}${memo.time ? ` (${memo.time})` : ''}`);
  }
  lines.push(`নাম: ${settings.userName || 'Iftikhar Ahmed'}`);
  lines.push('──────────────────────────');

  if (memo.type === 'market' && memo.marketItems) {
    memo.marketItems.forEach((item, index) => {
      const mark = item.isPurchased ? '☑' : '☐';
      const qty = `${formatNum(item.quantity, isBn)} ${item.unit}`;
      const price = showPrice && item.pricePerUnit
        ? ` — ${formatCurrency(item.quantity * item.pricePerUnit, settings.currency, isBn)}`
        : '';
      const note = item.note ? ` (${item.note})` : '';
      lines.push(`${mark} ${index + 1}. ${item.name}: ${qty}${price}${note}`);
    });
  } else if (isMedicine) {
    if (memo.medicineItems && memo.medicineItems.length > 0) {
      memo.medicineItems.forEach((med, index) => {
        const calc = calculateMedicine(med, isBn);
        const cost = showPrice && calc.estimatedCost > 0
          ? ` — ${formatCurrency(calc.estimatedCost, settings.currency, isBn)}`
          : '';
        const note = med.note ? ` (${med.note})` : '';
        lines.push(`${index + 1}. ${med.name}: ${calc.finalPurchaseLabelBn}${cost}${note}`);
        if (medicineExportType === 'full') {
          lines.push(`   (বর্তমান স্টক: ${calc.currentStockLabelBn} | প্রয়োজন: ${calc.monthlyNeedLabelBn})`);
        }
      });
    } else if (memo.requiredMedicineItems && memo.requiredMedicineItems.length > 0) {
      memo.requiredMedicineItems.forEach((med, index) => {
        const parts: string[] = [];
        if (med.strips > 0) parts.push(`${formatNum(med.strips, isBn)} পাতা`);
        if (med.pieces > 0) parts.push(`${formatNum(med.pieces, isBn)} পিস`);
        const qtyStr = parts.length > 0 ? parts.join(' + ') : '০';
        const cost =
          showPrice && med.unitPrice && med.unitPrice > 0
            ? ` — ${formatCurrency(
                med.priceType === 'strip' ? med.strips * med.unitPrice : med.pieces * med.unitPrice,
                settings.currency,
                isBn
              )}`
            : '';
        const note = med.note ? ` (${med.note})` : '';
        lines.push(`${index + 1}. ${med.name}: ${qtyStr}${cost}${note}`);
      });
    }
  }

  // Summary (only if showPrice is true)
  if (showPrice) {
    lines.push('──────────────────────────');
    lines.push(`মোট আনুমানিক খরচ: ${formatCurrency(memo.totalPrice || 0, settings.currency, isBn)}`);
  }

  // NO promotional tagline like "Generated by MY MEMO" (Requirement 4)
  return lines.join('\n');
}

export async function shareMemo(
  memo: SavedMemo,
  settings: UserSettings,
  format: 'image' | 'pdf' | 'text',
  options?: MemoExportOptions
): Promise<{ success: boolean; message: string }> {
  try {
    const title = memo.title || (memo.type.startsWith('medicine') ? 'ঔষধের মেমো' : 'বাজারের মেমো');

    if (format === 'text') {
      const text = formatMemoAsText(memo, settings, options);
      if (navigator.share) {
        await navigator.share({
          title,
          text,
        });
        return { success: true, message: 'সফলভাবে শেয়ার করা হয়েছে' };
      } else {
        await navigator.clipboard.writeText(text);
        return { success: true, message: 'টেক্সট ক্লিপবোর্ডে কপি করা হয়েছে!' };
      }
    }

    if (format === 'image') {
      const { blob } = await generateMemoImage(memo, settings, 'image/png', options);
      const filename = `${title.replace(/\s+/g, '_')}_${Date.now()}.png`;
      const file = new File([blob], filename, { type: 'image/png' });

      // Clean 2-line caption for JPG/Image share as explicitly requested:
      // তারিখ: [বর্তমান তারিখ] ([বর্তমান সময়])
      // নাম: [Settings থেকে পাওয়া নাম]
      const currentFormattedDate = getTodayFormatted(settings.dateFormat);
      const currentFormattedTime = getTimeFormatted();
      const userName = settings.userName || 'Iftikhar Ahmed';
      const imageShareCaption = `তারিখ: ${currentFormattedDate} (${currentFormattedTime})\nনাম: ${userName}`;

      if (navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({
          files: [file],
          title,
          text: imageShareCaption,
        });
        return { success: true, message: 'ছবি সফলভাবে শেয়ার করা হয়েছে' };
      } else {
        // Fallback: direct download
        downloadBlob(blob, filename);
        return { success: true, message: 'ছবি ডিভাইসে ডাউনলোড হয়েছে!' };
      }
    }

    if (format === 'pdf') {
      const { blob, filename } = await generateMemoPDF(memo, settings, options);
      const file = new File([blob], filename, { type: 'application/pdf' });

      if (navigator.canShare && navigator.canShare({ files: [file] })) {
        await navigator.share({
          files: [file],
          title,
          text: title,
        });
        return { success: true, message: 'PDF সফলভাবে শেয়ার করা হয়েছে' };
      } else {
        // Fallback: download PDF
        downloadPDF(blob, filename);
        return { success: true, message: 'PDF ডিভাইসে ডাউনলোড হয়েছে!' };
      }
    }

    return { success: false, message: 'অজানা ফরম্যাট' };
  } catch (err: any) {
    if (err.name === 'AbortError') {
      return { success: false, message: 'শেয়ার বাতিল করা হয়েছে' };
    }
    console.error('Share error:', err);
    return { success: false, message: 'শেয়ার করার সময় সমস্যা হয়েছে' };
  }
}
